# Generated by Django 4.0.4 on 2022-05-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Gps_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pfaApp.gps_loca'),
        ),
    ]
