# Generated by Django 4.0.4 on 2022-05-06 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfaApp', '0003_polygon_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xmin', models.FloatField()),
                ('ymin', models.FloatField()),
                ('xmax', models.FloatField()),
                ('ymax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=100)),
                ('bbox', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pfaApp.bbox')),
                ('polygon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pfaApp.polygon')),
            ],
        ),
    ]
