# Generated by Django 4.0.4 on 2022-05-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfaApp', '0004_bbox_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='objets',
            field=models.ManyToManyField(to='pfaApp.object'),
        ),
    ]
