# Generated by Django 4.0.4 on 2022-05-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfaApp', '0005_file_objets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='polygon',
        ),
        migrations.AddField(
            model_name='polygon',
            name='points',
            field=models.ManyToManyField(to='pfaApp.point'),
        ),
    ]
